# Generated by Django 6.0.7 on 2026-07-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('NEW', 'New'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('RETURNS', 'Returns & Dispute')], default='NEW', max_length=20),
        ),
    ]
