# Generated by Django 6.0.7 on 2026-07-15 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_deliveryboyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('ASSIGNING', 'Assigning Driver'), ('ACCEPTED', 'Accepted / In Progress'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_delivery_boy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_orders', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ManyToManyField(blank=True, related_name='rejected_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
