# Generated by Django 6.0.7 on 2026-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_assignmentattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
