# Generated by Django 6.0.7 on 2026-07-19 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_order_shop_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentattempt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Response'), ('ACCEPTED', 'Accepted'), ('TIMEOUT', 'Timed Out after 20 mins'), ('REJECTED', 'Rejected'), ('FORCED_BY_ADMIN', 'Forced by Admin Override')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_as_role', models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('CUSTOMER', 'Customer'), ('DELIVERY_BOY', 'Delivery Boy')], max_length=50)),
                ('category', models.CharField(choices=[('MISSING_ITEM', 'Missing Items in Order'), ('DAMAGE', 'Damaged Goods'), ('DELIVERY_ISSUE', 'Delivery Delay or Dispute'), ('PAYMENT', 'Payment / Refund Issue'), ('OTHER', 'General Inquiry')], default='OTHER', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent / Missing Items')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='accounts.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
