# Generated by Django 6.0.7 on 2026-07-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ['-media_type', 'created_at']},
        ),
    ]
