# Generated by Django 6.0.7 on 2026-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='latitude',
            new_name='delivery_latitude',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='longitude',
            new_name='delivery_longitude',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Payment Pending'), ('PAID', 'Payment Successful'), ('ASSIGNING', 'Assigning Driver'), ('SHIPPED', 'Shipped'), ('RETURNS', 'Returns & Dispute')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Payment Pending'), ('PAID', 'Payment Successful'), ('ASSIGNING', 'Assigning Driver'), ('SHIPPED', 'Shipped'), ('RETURNS', 'Returns & Dispute')], default='PENDING', max_length=20),
        ),
    ]
