# Generated by Django 6.0.7 on 2026-07-20 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_latitude_order_delivery_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, unique=True)),
                ('id_document', models.FileField(upload_to='seller_docs/ids/')),
                ('business_license', models.FileField(upload_to='seller_docs/licenses/')),
                ('tax_number', models.CharField(help_text='PAN or VAT number', max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('routing_number', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('bank_statement', models.FileField(upload_to='seller_docs/financials/')),
                ('warehouse_address', models.TextField(help_text='Physical pickup location for delivery couriers')),
                ('support_email', models.EmailField(max_length=254)),
                ('support_phone', models.CharField(max_length=20)),
                ('product_categories', models.TextField(help_text='Comma-separated list of intended categories')),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('ACTIVE', 'Approved/Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
