# Generated by Django 6.0.7 on 2026-07-20 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_sellerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text="e.g., 'pants for men', 'freeze 200l'", max_length=100, unique=True)),
                ('search_count', models.PositiveIntegerField(default=0, help_text='Track popularity')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
            ],
            options={
                'ordering': ['-search_count', 'keyword'],
            },
        ),
    ]
