# Generated by Django 6.0.7 on 2026-07-20 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_searchtag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average review rating out of 5.00', max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='relevant_tags',
            field=models.TextField(blank=True, help_text="Comma-separated plain text keywords for search indexing (e.g., 'summer, light, cotton')"),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.searchtag'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_bought',
            field=models.PositiveIntegerField(default=0, help_text='Total lifetime sales count'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews submitted'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_search_appears',
            field=models.PositiveIntegerField(default=0, help_text='How many times this product appeared in search results'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_views',
            field=models.PositiveIntegerField(default=0, help_text='Total product detail page views'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
