# Generated by Django 6.0.7 on 2026-07-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_average_rating_product_relevant_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#4F46E5', help_text='Hex color code (e.g., #4F46E5)', max_length=7),
        ),
    ]
