# Generated by Django 6.0.7 on 2026-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filter_schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object defining available filter keys/options'),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='JSON format properties (e.g. {"sub_type": "jeans", "size": "L"})'),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='relevant_tags',
            field=models.TextField(blank=True, help_text='Comma-separated plain text keywords for search indexing'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_bought',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_search_appears',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
